<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>feature_buy_product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f9ea17e3-1efa-4565-924f-91767875fe5c</testSuiteGuid>
   <testCaseLink>
      <guid>71be01cf-c397-46fc-b4cf-5c7b38c2775b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_bid_or_buy_product/BBP001 - Bid or buy product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f56546bc-9b10-49fe-99cc-9dea389efbe9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d965e567-6efe-48e3-9b56-7203f5c0e193</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_bid_or_buy_product/BBPhelper for change status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a29a314-1cc2-4e05-964a-4041ba8ec765</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
