<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>feature_decline_product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>578b9925-72ce-43d6-b54b-fe80dc29af91</testSuiteGuid>
   <testCaseLink>
      <guid>06ec28ec-8760-4a55-9474-7f1464e29d60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_decline_transaction/UTD001 - Decline bid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76b81f30-01b8-48f9-852f-704e62152eca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffb9bec7-a8cc-4627-a9dd-f3c222b82f97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed61c278-56a7-4981-a2f0-8f720556f868</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_decline_transaction/UTD002 - Change status to decline</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c934285b-0dae-4abb-bcc6-c1f5b5510b87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35655e4d-afdf-4cd5-ad4d-41aa00f28c4d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
