<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>feature_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c8c4c2a7-0ab5-450c-ad8c-8e37b23789b3</testSuiteGuid>
   <testCaseLink>
      <guid>bd05b97e-ec43-4d91-a631-7ae4cdec0f25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI001 - User want to login by using correct credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b80f7834-c903-466c-a8a6-c3d236c03ed5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b601d794-afa5-4213-8745-93267e04bfaf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf2eacd9-ad9e-490f-ae36-134ea7e1f756</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI002 - User want to login by not filling all field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>85b58ffd-40ac-4685-8140-053f4595a238</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI003 - User want to login by using incorrect email credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ef1673d-e294-4a86-8fb2-b6c2f51755e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7866d6e0-9651-48b8-9315-f2a18258cfbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef41de79-d8dd-44e5-a58e-8b498b12d344</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI004 - User want to login by using incorrect password credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e661bcae-2a8d-4aa3-b3e8-6f3d2cc2a57d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78aef0f9-9644-4e2b-ba1d-e1cdbce49e4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3d22ed5-98b2-4db9-b9b6-ea49c116fca4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI005 - User want to login by input incorrect email format on email textfield</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc1ee1cd-35ef-4f3f-b2b3-ef117fbc006d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e63ee925-033d-4f05-b155-1dddbbcafdc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>036e0b28-965b-4f86-b126-a6817c5c4414</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI006 - User want to login by input incorrect password format on password textfield</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14fcd57c-f417-4890-8650-e0c687d4dedb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af7e6593-3a51-4287-bf5e-91a290bec339</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>745ee841-aebe-4a85-babf-a09ef584a21a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI007 - User want to login by reveal his password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>969771a8-e1e9-4702-afb0-1f15adf77e01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f92d4ef1-17c3-464d-8511-bb5a869e8987</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f83a23bf-2a63-43d0-8a38-2a6aeb548ab0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI008 - User want to login by hide his password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be6de6cf-194a-44e9-8dbc-c7e040ed69e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31ecdeb9-4027-4c0b-af13-d6ea4a239535</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
